### ISSUE TITLE
Compatibility with micro:bit v2

### ISSUE THREAD

**Issue by microbit-sam** [Tinkertanker/pxt-alphanumeric-ht16k33#3]
Hi @tinkertanker ,

As you might have seen from microsoft/pxt-microbit#3506 this extension is currently not compiling against the latest version of Micro:bit CODAL. This means it will not work with micro:bit V2.

Software for micro:bit V2 boards is built using CODAL rather than the DAL, and no longer includes the mbed layer. We’ve implemented the most frequently used mbed classes to support easy porting of existing extensions, but there may still be corner cases with this compatibility layer.

As your extension is currently not building, it will be disabled for micro:bit V2. People attempting to use your extension with a micro:bit V2 board will get error 929. This extension will only be re-enabled on micro:bit V2 once it is fixed.

There are details on how to ensure extensions work on both version of the micro:bit here (lancaster-university/codal-microbit-v2#31).

Looking at your extension source I believe that your extension falls under this category:

> Use of mbed APIs that are not included in the compatibility layer, or microbit-dal APIs that need different constructors

I2C compatibility is being looked at, as there a few broken edge cases. Updates will be tracked in lancaster-university/codal-microbit-v2#31

**Comment by microbit-pauline** [comment]
@firemansamm - Are you able to look at this issue?

**Comment by Mireille-T** [comment]
This issue has been resolved with the latest release of the extension. Thank you! 😄
